import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F6F9',
    padding: 20,
    justifyContent: 'center', // Centra o conteúdo verticalmente
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    backgroundColor: '#FFF',
    padding: 25,
    borderRadius: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    alignItems: 'center', // Centra os elementos dentro do cartão
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: '#2C3E50',
    marginBottom: 20,
    textAlign: 'center',
  },
  avatarContainer: {
    marginBottom: 20,
    alignItems: 'center',
    position: 'relative',
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#EAECEE',
    borderWidth: 3,
    borderColor: '#1A5276',
  },
  avatarPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#EAECEE',
    borderWidth: 3,
    borderColor: '#1A5276',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editAvatarButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#E74C3C',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFF',
    elevation: 4,
  },
  orgBadge: {
    backgroundColor: '#E8F8F5',
    padding: 12,
    borderRadius: 10,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#117A65',
    width: '100%',
    alignItems: 'center',
  },
  orgBadgeTitle: {
    color: '#117A65',
    fontWeight: 'bold',
    fontSize: 13,
    marginBottom: 2,
  },
  orgBadgeName: {
    color: '#117A65',
    fontSize: 15,
  },
  inputGroup: {
    width: '100%',
    marginBottom: 15,
  },
  label: {
    color: '#7F8C8D',
    fontWeight: '600',
    fontSize: 13,
    marginBottom: 6,
    alignSelf: 'flex-start',
  },
  disabledInput: {
    backgroundColor: '#EAECEE',
    padding: 14,
    borderRadius: 10,
    color: '#7F8C8D',
    fontSize: 15,
    width: '100%',
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#FAFAFA',
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DDD',
    fontSize: 15,
    color: '#2C3E50',
    width: '100%',
    textAlign: 'center',
  },
  saveButton: {
    backgroundColor: '#1A5276',
    paddingVertical: 16,
    borderRadius: 10,
    alignItems: 'center',
    width: '100%',
    marginTop: 10,
    elevation: 2,
  },
  saveButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  backButton: {
    marginTop: 25,
    alignItems: 'center',
  },
  backButtonText: {
    color: '#E74C3C',
    fontWeight: '700',
    fontSize: 15,
  }
});